name: jsonplaceholder_client
description: A jsonplaceholder client for Dart.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.3.1
  fresh_dio: ^0.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
